test:
    uv run pytest tests

coverage:
    uv run coverage run -m pytest tests
    uv run coverage combine
    uv run coverage report

typecheck:
    uv run mypy src/

format:
    uv run ruff check src tests --fix
    uv run shed
    uv run ruff format src tests

lint:
    ruff check .
    shed --check .

check: typecheck lint coverage
